#!/usr/bin/env python3
#
# Skald - Copyright (C) 2026 Gard Kroken
# SPDX-License-Identifier: Apache-2.0
#

"""The build worker's two runtime artifacts, shipped as files and checked against the
definitions the T3/T5 probes measured (WORKPLAN-BUNDLES.md T7, part 3).

  spec/build-worker-seccomp-v1.json   the worker's seccomp profile: Docker's default at the
                                      pinned commit plus the measured additions
                                      (buildkit_worker_profile.write)
  images/buildkit-worker/Dockerfile   the derived worker image (shipping_worker.
                                      worker_dockerfile), below a comment header

The probes generate both at run time. buildkit_worker_profile.py's docstring says so: "T7
owns what a deployment actually ships". The server cannot fetch from GitHub at launch, and
it should not run something nobody reviewed, so the deployment gets reviewed files. This
check keeps the shipped files from drifting from what the probes measure: a profile edited
by hand, or an addition made to the generator and not shipped, fails here. The profile is
compared as JSON (the shipped one is indented for review); the Dockerfile as text.

Usage: python3 dev/worker-artifacts.py [--write | --self-test]
  (no flag)    check both; exit 1 on any difference
  --write      regenerate both (then review the diff)
  --self-test  each check must fail on a file that differs in one measured respect
"""

import json
import pathlib
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import buildkit_worker_profile as bwp  # noqa: E402
import shipping_worker  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
SECCOMP = REPO / "spec/build-worker-seccomp-v1.json"
DOCKERFILE = REPO / "images/buildkit-worker/Dockerfile"
HEADER = """\
# Skald build worker: rootless BuildKit, derived from the pinned upstream (WORKPLAN-BUNDLES.md
# "Build sandbox and dependency network"; T3/T5 measured it, T7 ships it). GENERATED by
# dev/worker-artifacts.py --write from dev/shipping_worker.py; checked by the same script.
# Built by the operator when maintaining the platform, never by an upload.
#
# The identity is dedicated (uid 2401, subordinate ids 3000000+): unassigned on the host,
# so an escape does not land on a real account. The two setuid/setgid helpers the upstream
# carries beyond the uid-map tools are cleared, because no-new-privileges is waived for
# runc-rootless (user sign-off 2026-09-26; spec runtimes.runc-rootless.waived).
"""


def generated_seccomp():
    with tempfile.TemporaryDirectory() as d:
        base = bwp.fetch_default(d)
        return json.loads(pathlib.Path(bwp.write(d, base)).read_text())


def generated_dockerfile():
    return HEADER + shipping_worker.worker_dockerfile()


def judge_seccomp(shipped_text, generated):
    try:
        shipped = json.loads(shipped_text)
    except ValueError as e:
        return False, "not JSON: %s" % e
    if shipped != generated:
        extra = [s for s in shipped.get("syscalls", []) if s not in generated["syscalls"]]
        missing = [s for s in generated["syscalls"] if s not in shipped.get("syscalls", [])]
        return False, "differs from the generator: %d rule(s) only shipped, %d only generated" \
            % (len(extra), len(missing))
    return True, "equal to the generator's (%d rules)" % len(generated["syscalls"])


def judge_dockerfile(shipped_text, generated):
    if shipped_text != generated:
        return False, "differs from shipping_worker.worker_dockerfile()"
    return True, "equal to the generator's"


def main(argv):
    seccomp, dockerfile = generated_seccomp(), generated_dockerfile()
    if "--write" in argv:
        SECCOMP.write_text(json.dumps(seccomp, indent=2) + "\n")
        DOCKERFILE.parent.mkdir(parents=True, exist_ok=True)
        DOCKERFILE.write_text(dockerfile)
        print("wrote %s and %s" % (SECCOMP.relative_to(REPO), DOCKERFILE.relative_to(REPO)))
        return 0
    if "--self-test" in argv:
        return self_test(seccomp, dockerfile)
    bad = 0
    for label, (ok, detail) in (
            ("seccomp", judge_seccomp(SECCOMP.read_text(), seccomp)),
            ("dockerfile", judge_dockerfile(DOCKERFILE.read_text(), dockerfile))):
        print("  %-6s %-12s %s" % ("ok" if ok else "FAIL", label, detail))
        bad += not ok
    print("RESULT:", "the shipped worker artifacts are the measured ones" if not bad
          else "%d artifact(s) drifted" % bad)
    return 1 if bad else 0


def self_test(seccomp, dockerfile):
    missed = []

    def expect(label, judged, want):
        ok, detail = judged
        print("  %s %s (%s)" % ("ok  " if ok == want else "FAIL", label, detail[:80]))
        if ok != want:
            missed.append(label)

    shipped = SECCOMP.read_text()
    doc = json.loads(shipped)
    expect("the shipped profile passes", judge_seccomp(shipped, seccomp), True)
    no_pivot = json.loads(shipped)
    for rule in no_pivot["syscalls"]:
        if rule["names"] == bwp.ALLOWED:
            rule["names"] = [n for n in rule["names"] if n != "pivot_root"]
    expect("a profile without pivot_root is caught", judge_seccomp(json.dumps(no_pivot), seccomp),
           False)
    widened = json.loads(shipped)
    widened["syscalls"].append({"names": ["bpf"], "action": "SCMP_ACT_ALLOW"})
    expect("a profile allowing one more syscall is caught",
           judge_seccomp(json.dumps(widened), seccomp), False)
    keyctl = json.loads(shipped)
    keyctl["syscalls"] = [r for r in keyctl["syscalls"] if r["names"] != ["keyctl"]]
    expect("a profile without the keyctl ENOSYS rule is caught",
           judge_seccomp(json.dumps(keyctl), seccomp), False)
    default_action = dict(doc, defaultAction="SCMP_ACT_ALLOW")
    expect("a default-allow profile is caught",
           judge_seccomp(json.dumps(default_action), seccomp), False)
    text = DOCKERFILE.read_text()
    expect("the shipped Dockerfile passes", judge_dockerfile(text, dockerfile), True)
    expect("a Dockerfile keeping the setuid helpers is caught", judge_dockerfile(
        text.replace("RUN chmod u-s,g-s /usr/bin/fusermount3 /usr/sbin/unix_chkpwd\n", ""),
        dockerfile), False)
    expect("a Dockerfile running the worker as root is caught",
           judge_dockerfile(text.replace("USER 2401:2401", "USER root"), dockerfile), False)
    print("RESULT:", "self-test passed" if not missed else "self-test FAILED: " + ", ".join(missed))
    return 1 if missed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
