/*
 * Skald
 *
 * Copyright (C) 2026 Gard Kroken
 *
 * Built on ShinyProxy, Copyright (C) 2016-2026 Open Analytics NV.
 *
 * ===========================================================================
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Apache License as published by
 * The Apache Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Apache License for more details.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/>
 */
package eu.openanalytics.shinyproxy.publisher.worker;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import eu.openanalytics.shinyproxy.publisher.worker.WorkerProfile.Launch;
import eu.openanalytics.shinyproxy.publisher.worker.WorkerProfile.Settings;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * The launch WorkerProfile computes, against what the docker CLI made of the same profile
 * arguments (dev/fixtures/worker/cli-hostconfig.json, regenerated by
 * dev/worker-artifacts.py --write), and the refusals the spec's refuse-to-start rule asks for.
 */
public class WorkerProfileTest {

    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Path RECORD = Path.of("dev/fixtures/worker/cli-hostconfig.json");
    private static final Path SPEC = Path.of("spec/isolation-profile-v1.json");

    @Test
    public void theDefaultsAreTheValuesTheCliRecordWasMadeAt() {
        JsonNode values = record().path("values");
        Settings d = Settings.defaults();
        assertEquals(values.path("cpu_quota").asText(), d.cpuQuota());
        assertEquals(values.path("memory_limit").asText(), d.memoryLimit());
        assertEquals(values.path("pid_limit").asText(), d.pidLimit());
        assertEquals(values.path("tmpfs_size").asText(), d.tmpfsSize());
        assertEquals(values.path("step_log_max_bytes").asText(), d.stepLogMaxBytes());
        assertEquals(values.path("step_log_max_bytes_per_second").asText(), d.stepLogMaxBytesPerSecond());
        assertEquals(record().path("runtime").asText(), "runc-rootless");
    }

    @Test
    public void theLaunchIsWhatTheCliMadeOfTheSameArguments() {
        Launch l = WorkerProfile.load("runc-rootless").launch(Settings.defaults(), "skald-net", "skald-vol");
        JsonNode hc = record().path("host_config");
        assertEquals(hc.path("NanoCpus").asLong(), l.nanoCpus());
        assertEquals(hc.path("Memory").asLong(), l.memory());
        assertEquals(hc.path("MemorySwap").asLong(), l.memorySwap());
        assertEquals(hc.path("PidsLimit").asInt(), l.pidsLimit());
        assertEquals(hc.path("ReadonlyRootfs").asBoolean(), l.readOnlyRootfs());
        assertEquals(JSON.convertValue(hc.path("Tmpfs"), Map.class), l.tmpfs());
        assertEquals(hc.path("NetworkMode").asText(), l.networkMode().replace("skald-net", "<egress_network>"));
        assertEquals(strings(hc.path("Binds")), l.binds().stream()
                .map(b -> b.replace("skald-vol", "<quota_volume>")).toList());
        // The CLI sends the seccomp file compacted; the record keeps its hash.
        assertEquals(strings(hc.path("SecurityOpt")), l.securityOpt().stream()
                .map(o -> o.startsWith("seccomp=") ? "seccomp=sha256:" + sha256(o.substring(8)) : o)
                .toList());
        // The record is sorted (the CLI's order varies); an environment is a set.
        assertEquals(strings(record().path("env")), l.env().stream().sorted().toList());
        assertFalse(hc.path("Privileged").asBoolean(true));
    }

    @Test
    public void everyRefusalTheSpecAsksForHappens() {
        List<String> started = new ArrayList<>();
        refuse(started, "an unknown runtime", s -> { }, "runsc");
        refuse(started, "a runtime that is not selectable",
                s -> runtime(s).put("selectable", false), "runc-rootless");
        refuse(started, "a runtime that is not measured",
                s -> runtime(s).put("status", "candidate"), "runc-rootless");
        refuse(started, "a runtime that does not enforce the memory limit", s -> {
            ArrayNode enforces = (ArrayNode) runtime(s).get("enforces");
            for (int i = 0; i < enforces.size(); i++) {
                if (enforces.get(i).asText().equals("memory limit")) {
                    enforces.remove(i);
                    return;
                }
            }
            throw new IllegalStateException("the mutant did not apply");
        }, "runc-rootless");
        // The waiver is load-bearing: without it, no-new-privileges is required, and the
        // rootless runtime does not enforce it.
        refuse(started, "no-new-privileges no longer waived",
                s -> ((ObjectNode) runtime(s)).remove("waived"), "runc-rootless");
        refuse(started, "a forbidden argument as a bound",
                s -> bound(s, "read_only_rootfs").put("argument", "--privileged"), "runc-rootless");
        // A forbidden argument the form parser WOULD accept: only the forbidden list stops it.
        refuse(started, "the host network as the profile's network",
                s -> bound(s, "network").put("argument", "--network=host"), "runc-rootless");
        refuse(started, "seccomp unconfined",
                s -> bound(s, "seccomp").put("argument", "--security-opt=seccomp=unconfined"),
                "runc-rootless");
        refuse(started, "no forbidden list at all",
                s -> ((ObjectNode) s.path("profiles").path("build-worker")).remove("forbidden_arguments"),
                "runc-rootless");
        refuse(started, "an argument form the launcher cannot express",
                s -> bound(s, "cpu").put("argument", "--cpu-quota=<cpu_quota>"), "runc-rootless");
        // Forms on bounds no completeness check covers: dropping them silently would launch
        // without a scratch bound or with a writable root.
        refuse(started, "the scratch tmpfs as --mount",
                s -> bound(s, "scratch").put("argument", "--mount=type=tmpfs,destination=/tmp"),
                "runc-rootless");
        refuse(started, "read-only spelled --read-only=true",
                s -> bound(s, "read_only_rootfs").put("argument", "--read-only=true"), "runc-rootless");
        refuse(started, "a placeholder nothing fills",
                s -> bound(s, "memory").put("argument", "--memory=<mem>"), "runc-rootless");
        refuse(started, "a second cpu bound", s -> ((ObjectNode) s.path("profiles").path("build-worker")
                .path("bounds")).set("cpu2", bound(s, "cpu").deepCopy()), "runc-rootless");
        refuse(started, "no seccomp bound", s -> ((ObjectNode) s.path("profiles").path("build-worker")
                .path("bounds")).remove("seccomp"), "runc-rootless");
        assertEquals(List.of(), started);
    }

    @Test
    public void settingsAndNamesAreCheckedBeforeTheyReachAnArgument() {
        for (String cpu : List.of("0", "-1", "2; rm -rf /", "1e3", "2 ", "")) {
            assertThrows(IllegalArgumentException.class,
                    () -> new Settings(cpu, "4g", "512", "256m", "1", "1"), cpu);
        }
        for (String mem : List.of("4G", "4gb", "0", "-4g", "4g,size=1", "")) {
            assertThrows(IllegalArgumentException.class,
                    () -> new Settings("2", mem, "512", "256m", "1", "1"), mem);
        }
        for (String n : List.of("0", "-1", "512 ", "5e2")) {
            assertThrows(IllegalArgumentException.class,
                    () -> new Settings("2", "4g", n, "256m", "1", "1"), n);
        }
        WorkerProfile p = WorkerProfile.load("runc-rootless");
        for (String name : List.of("a/b", "a b", "x:/etc", "--privileged", "")) {
            assertThrows(IllegalArgumentException.class, () -> p.launch(Settings.defaults(), name, "vol"), name);
            assertThrows(IllegalArgumentException.class, () -> p.launch(Settings.defaults(), "net", name), name);
        }
        // Docker's own networks are plain names, so the name rule alone would pass them.
        for (String reserved : List.of("host", "bridge", "default", "none")) {
            assertThrows(IllegalArgumentException.class,
                    () -> p.launch(Settings.defaults(), reserved, "vol"), reserved);
        }
        assertEquals(4L << 30, WorkerProfile.bytes("4g"));
        assertEquals(256L << 20, WorkerProfile.bytes("256m"));
        assertEquals(512L, WorkerProfile.bytes("512"));
        assertThrows(IllegalStateException.class, () -> WorkerProfile.bytes("999999999999999g"));
    }

    // ------------------------------------------------------------------ helpers

    private static void refuse(List<String> started, String label, Consumer<ObjectNode> mutation,
                               String runtime) {
        ObjectNode spec = spec();
        mutation.accept(spec);
        try {
            WorkerProfile.parse(spec, runtime, "{}").launch(Settings.defaults(), "net", "vol");
            started.add(label);
        } catch (IllegalStateException expected) {
            // refused to start
        }
    }

    private static ObjectNode runtime(ObjectNode spec) {
        return (ObjectNode) spec.path("seam").path("runtimes").path("runc-rootless");
    }

    private static ObjectNode bound(ObjectNode spec, String name) {
        JsonNode b = spec.path("profiles").path("build-worker").path("bounds").path(name);
        if (b.isMissingNode()) {
            throw new IllegalStateException("no bound " + name + "; the case proves nothing");
        }
        return (ObjectNode) b;
    }

    private static List<String> strings(JsonNode array) {
        List<String> out = new ArrayList<>();
        array.forEach(n -> out.add(n.asText()));
        return out;
    }

    private static ObjectNode spec() {
        try {
            return (ObjectNode) JSON.readTree(SPEC.toFile());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static JsonNode record() {
        try {
            return JSON.readTree(RECORD.toFile());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String sha256(String s) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(s.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
